services:
  coder-derp:
    image: sparanoid/derp:master
    container_name: coder-derp
    networks:
      - coder_default
    restart: always
    init: true
    ports:
      - "39080:80/tcp"
      - "39443:443/tcp"
      - "33478:3478/udp"
    profiles: ['middleware']
    command:
      - derper
      - -hostname=192.168.100.204
      - -certmode=manual
      - -verify-clients=false
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  coder:
    # This MUST be stable for our documentation and
    # other automations.
    #image: registry.cn-beijing.aliyuncs.com/dc_huzy/coder:${CODER_VERSION:-latest}
    image: ghcr.io/coder/coder:v2.27.1-devel-29e38b876-amd64
    networks:
      - coder_default
    ports:
      - "7080:7080"
    profiles: ['app']
    restart: unless-stopped
    environment:
      #HTTP_PROXY: "http://192.168.100.218:10808"
      #HTTPS_PROXY: "http://192.168.100.218:10808"
      #NO_PROXY: "localhost,127.0.0.1,127.0.0.11,127.0.0.53,192.168.100.218,database"
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      # You'll need to set CODER_ACCESS_URL to an IP or domain
      # that workspaces can reach. This cannot be localhost
      # or 127.0.0.1 for non-Docker templates!
      CODER_ACCESS_URL: "${CODER_ACCESS_URL}"
      TF_SKIP_PROVIDER_VERIFY: 1
      CODER_OFFLINE_LICENSE_FILE: /home/coder/keys/license.jwt
      CODER_OFFLINE_PUBLIC_KEY_FILE: /home/coder/keys/coder-publickey.pem
      CODER_DERP_SERVERS: '[{"region":"private","hostname":"192.168.100.204","port":39443,"insecure":true}]'
      CODER_DERP_SERVER_STUN_ADDRESSES: "disable"
    # If the coder user does not have write permissions on
    # the docker socket, you can uncomment the following
    # lines and set the group ID to one that has write
    # permissions on the docker socket.
    group_add:
      - "994" # docker group on host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Run "docker volume rm coder_coder_home" to reset the dev tunnel url (https://abc.xyz.try.coder.app).
      # This volume is not required in a production environment - you may safely remove it.
      # Coder can recreate all the files it needs on restart.
      - ./home:/home/coder
      #- ./coder-cache:/home/coder/.cache/coder
      #- ./coder-terraformd:/home/coder/.terraform.d
      #- ./terraform.lock.hcl:/home/coder/.cache/coder/.terraform.lock.hcl
      - ./terraform:/home/coder/.terraform
      - ./terraform.lock.hcl:/home/coder/.terraform.lock.hcl
      - ./terraform-providers:/providers
      - ./terraform.rc:/home/coder/.terraformrc
      - ./terraform.rc:/root/.terraformrc
      - ./modules:/home/coder/.cache/coder/modules
      - ./keys:/home/coder/keys
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      database:
        condition: service_healthy
      coder-derp:
        condition: service_started
  database:
    # Minimum supported version is 13.
    # More versions here: https://hub.docker.com/_/postgres
    image: "registry.cn-beijing.aliyuncs.com/dc_huzy/postgres:17"
    networks:
      - coder_default
    # Uncomment the next two lines to allow connections to the database from outside the server.
    ports:
      - "45432:5432"
    profiles: ['middleware']
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username} # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: ${POSTGRES_DB:-coder} # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - ./data:/var/lib/postgresql/data # Use "docker volume rm coder_coder_data" to reset Coder
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      #- ./pg_hba.conf:/tmp/pg_hba.conf
    #command: ["cp /tmp/pg_hba.conf /var/lib/postgresql/data/", "postgres"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  coder_default:
    external: true
    name: coder_default
  default:
    driver: bridge
