#version: "3"
networks:
  ai-forge-dev:
    external: false

services:
  coder-ai-forge:
    #image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
    image: registry.cn-beijing.aliyuncs.com/dc_huzy/coder:${CODER_VERSION:-latest}
    container_name: coder-ai-forge
    restart: unless-stopped
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${CODER_POSTGRES_USER:-coder}:${CODER_POSTGRES_PASSWORD:-Coder0926!}@coder-db-ai-forge/${CODER_POSTGRES_DB:-coder}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "${CODER_ACCESS_URL}"
      #TF_SKIP_PROVIDER_VERIFY: 1
    env_file:
      - .env
    networks:
      - ai-forge-dev
    ports:
      - "47080:7080"
    group_add:
      - "${DOCKER_GROUP_NUM}"
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - ./coder-home:/home/coder
      - ./coder-cache:/home/coder/.cache/coder
      #- ./coder-terraform:/home/coder/.terraform
      - ./coder-terraform-providers:/providers
      - ./coder-terraformrc:/home/coder/.terraformrc
      - ./coder-terraformrc:/root/.terraformrc
      - ./coder-modules:/home/coder/.cache/coder/modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      coder-db-ai-forge:
        condition: service_healthy
  coder-db-ai-forge:
    #image: "postgres:17"
    image: "registry.cn-beijing.aliyuncs.com/dc_huzy/postgres:17"
    container_name: coder-db-ai-forge
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${CODER_POSTGRES_USER:-coder}
      POSTGRES_PASSWORD: ${CODER_POSTGRES_PASSWORD:-Coder0926!}
      POSTGRES_DB: ${CODER_POSTGRES_DB:-coder}
    networks:
      - ai-forge-dev
    ports:
      - "45432:5432"
    volumes:
      - ./coder-pg-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - /etc/localtime:/etc/localtime
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${CODER_POSTGRES_USER:-username} -d ${CODER_POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  gitea-ai-forge:
    image: registry.cn-beijing.aliyuncs.com/dc_huzy/gitea:1.24.6
    container_name: gitea-ai-forge
    restart: unless-stopped
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: ${GITEA_POSTGRES_HOST:-gitea-db-ai-forge}:5432
      GITEA__database__NAME: ${GITEA_POSTGRES_DB:-gitea}
      GITEA__database__PASSWD: ${GITEA_POSTGRES_PASSWORD:-Gitea0926!}
    networks:
      - ai-forge-dev
    ports:
      - "43000:3000"
      - "43022:22"
    volumes:
      - ./gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gitea-db-ai-forge
  gitea-db-ai-forge:
    image: registry.cn-beijing.aliyuncs.com/dc_huzy/postgres:17
    container_name: gitea-db-ai-forge
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${GITEA_POSTGRES_USER:-gitea}
      POSTGRES_PASSWORD: ${GITEA_POSTGRES_PASSWORD:-Gitea0926!}
      POSTGRES_DB: ${GITEA_POSTGRES_DB:-gitea}
    networks:
      - ai-forge-dev
    ports:
      - "45433:5432"
    volumes:
      - ./gitea-pg-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - /etc/localtime:/etc/localtime
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${GITEA_POSTGRES_USER:-postgres} -d ${GITEA_POSTGRES_DB:-gitea}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  nexus-ai-forge:
    image: "registry.cn-beijing.aliyuncs.com/dc_huzy/nexus3:3.61.0"
    container_name: nexus-ai-forge
    restart: unless-stopped
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data"
    networks:
      - ai-forge-dev
    ports:
      - 48081:8081
    volumes:
      - /etc/localtime:/etc/localtime
      - ./nexus/data/nexus-data:/nexus-data
  jenkins-ai-forge:
    image: "registry.cn-beijing.aliyuncs.com/dc_huzy/jenkins:2.507-jdk17"
    container_name: jenkins-ai-forge
    restart: unless-stopped
    privileged: true
    networks:
      - ai-forge-dev
    ports:
      - 48080:8080
    group_add:
      - "${DOCKER_GROUP_NUM}"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./jenkins/data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
