services:
  coder-derp:
    image: sparanoid/derp:master
    container_name: coder-derp
    networks:
      - coder_default
    restart: always
    init: true
    ports:
      - "39080:80/tcp"
      - "39443:443/tcp"
      - "33478:3478/udp"
    profiles: ['middleware']
    command:
      - derper
      - -hostname=192.168.100.204
      - -certmode=manual
      - -verify-clients=false
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  coder-ai-forge:
    #image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
    image: registry.cn-beijing.aliyuncs.com/dc_huzy/coder:${CODER_VERSION:-latest}
    container_name: coder-ai-forge
    # This MUST be stable for our documentation and
    # other automations.
    #image: registry.cn-beijing.aliyuncs.com/dc_huzy/coder:${CODER_VERSION:-latest}
    #image: ghcr.io/coder/coder:v2.27.1-devel-29e38b876-amd64
    networks:
      - coder_default
    ports:
      - "7080:7080"
    profiles: ['app']
    restart: unless-stopped
    environment:
      #HTTP_PROXY: "http://192.168.100.218:10808"
      #HTTPS_PROXY: "http://192.168.100.218:10808"
      #NO_PROXY: "localhost,127.0.0.1,127.0.0.11,127.0.0.53,192.168.100.218,database"
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      # You'll need to set CODER_ACCESS_URL to an IP or domain
      # that workspaces can reach. This cannot be localhost
      # or 127.0.0.1 for non-Docker templates!
      CODER_ACCESS_URL: "${CODER_ACCESS_URL}"
      #TF_SKIP_PROVIDER_VERIFY: 1
    env_file:
      - .env
    networks:
      - ai-forge-dev
    ports:
      - "47080:7080"
      TF_SKIP_PROVIDER_VERIFY: 1
      CODER_OFFLINE_LICENSE_FILE: /home/coder/keys/license.jwt
      CODER_OFFLINE_PUBLIC_KEY_FILE: /home/coder/keys/coder-publickey.pem
      CODER_DERP_SERVERS: '[{"region":"private","hostname":"192.168.100.204","port":39443,"insecure":true}]'
      CODER_DERP_SERVER_STUN_ADDRESSES: "disable"
    # If the coder user does not have write permissions on
    # the docker socket, you can uncomment the following
    # lines and set the group ID to one that has write
    # permissions on the docker socket.
    group_add:
      - "994" # docker group on host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./coder-home:/home/coder
      - ./coder-cache:/home/coder/.cache/coder
      #- ./coder-terraform:/home/coder/.terraform
      - ./coder-terraform-providers:/providers
      - ./coder-terraformrc:/home/coder/.terraformrc
      - ./coder-terraformrc:/root/.terraformrc
      - ./coder-modules:/home/coder/.cache/coder/modules
      # Run "docker volume rm coder_coder_home" to reset the dev tunnel url (https://abc.xyz.try.coder.app).
      # This volume is not required in a production environment - you may safely remove it.
      # Coder can recreate all the files it needs on restart.
      - ./home:/home/coder
      #- ./coder-cache:/home/coder/.cache/coder
      #- ./coder-terraformd:/home/coder/.terraform.d
      #- ./terraform.lock.hcl:/home/coder/.cache/coder/.terraform.lock.hcl
      - ./terraform:/home/coder/.terraform
      - ./terraform.lock.hcl:/home/coder/.terraform.lock.hcl
      - ./terraform-providers:/providers
      - ./terraform.rc:/home/coder/.terraformrc
      - ./terraform.rc:/root/.terraformrc
      - ./modules:/home/coder/.cache/coder/modules
      - ./keys:/home/coder/keys
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      database:
        condition: service_healthy
  coder-db-ai-forge:
    #image: "postgres:17"
    image: "registry.cn-beijing.aliyuncs.com/dc_huzy/postgres:17"
    container_name: coder-db-ai-forge
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${CODER_POSTGRES_USER:-coder}
      POSTGRES_PASSWORD: ${CODER_POSTGRES_PASSWORD:-Coder0926!}
      POSTGRES_DB: ${CODER_POSTGRES_DB:-coder}
      coder-derp:
        condition: service_started
  database:
    # Minimum supported version is 13.
    # More versions here: https://hub.docker.com/_/postgres
    image: "registry.cn-beijing.aliyuncs.com/dc_huzy/postgres:17"
    networks:
      - coder_default
    # Uncomment the next two lines to allow connections to the database from outside the server.
    ports:
      - "45432:5432"
    profiles: ['middleware']
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username} # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: ${POSTGRES_DB:-coder} # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - ./data:/var/lib/postgresql/data # Use "docker volume rm coder_coder_data" to reset Coder
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      #- ./pg_hba.conf:/tmp/pg_hba.conf
    #command: ["cp /tmp/pg_hba.conf /var/lib/postgresql/data/", "postgres"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  gitea-ai-forge:
    image: registry.cn-beijing.aliyuncs.com/dc_huzy/gitea:1.24.6
    container_name: gitea-ai-forge
    restart: unless-stopped
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: ${GITEA_POSTGRES_HOST:-gitea-db-ai-forge}:5432
      GITEA__database__NAME: ${GITEA_POSTGRES_DB:-gitea}
      GITEA__database__PASSWD: ${GITEA_POSTGRES_PASSWORD:-Gitea0926!}
    networks:
      - ai-forge-dev
    ports:
      - "43000:3000"
      - "43022:22"
    volumes:
      - ./gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gitea-db-ai-forge
  gitea-db-ai-forge:
    image: registry.cn-beijing.aliyuncs.com/dc_huzy/postgres:17
    container_name: gitea-db-ai-forge
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${GITEA_POSTGRES_USER:-gitea}
      POSTGRES_PASSWORD: ${GITEA_POSTGRES_PASSWORD:-Gitea0926!}
      POSTGRES_DB: ${GITEA_POSTGRES_DB:-gitea}
    networks:
      - ai-forge-dev
    ports:
      - "45433:5432"
    volumes:
      - ./gitea-pg-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - /etc/localtime:/etc/localtime
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${GITEA_POSTGRES_USER:-postgres} -d ${GITEA_POSTGRES_DB:-gitea}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  nexus-ai-forge:
    image: "registry.cn-beijing.aliyuncs.com/dc_huzy/nexus3:3.61.0"
    container_name: nexus-ai-forge
    restart: unless-stopped
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data"
    networks:
      - ai-forge-dev
    ports:
      - 48081:8081
    volumes:
      - /etc/localtime:/etc/localtime
      - ./nexus/data/nexus-data:/nexus-data
  jenkins-ai-forge:
    image: "registry.cn-beijing.aliyuncs.com/dc_huzy/jenkins:2.507-jdk17"
    container_name: jenkins-ai-forge
    restart: unless-stopped
    privileged: true
    networks:
      - ai-forge-dev
    ports:
      - 48080:8080
    group_add:
      - "${DOCKER_GROUP_NUM}"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./jenkins/data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  coder_default:
    external: true
    name: coder_default
  default:
    driver: bridge
